services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alfamaDB
      MYSQL_USER: alfama
      MYSQL_PASSWORD: alfama
    ports:
      - "3340:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data: